name: Atualizar RSS

on:
  schedule:
    - cron: '0 9,18 * * *'
  workflow_dispatch:

# Permissão VIP obrigatória para o robô poder salvar arquivos
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Repositorio
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Libs
        run: pip install -r requirements.txt
        
      - name: Rodar Scraper
        run: python main.py
        
      - name: Forçar Salvação no GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Feed atualizado automaticamente com as últimas notícias"
          file_pattern: 'feed.xml'
          commit_user_name: "BunnyRunnerX Bot"
          commit_user_email: "bot@actions.github.com"
